const rewards = [
  {
    title: "Maratón de Películas",
    category: "Ocio",
    description: "Un paquete de suscripción para ver películas ilimitadas.",
    imageUrl: "/assets/cine.png",
    points: 300,
    stock: 5,
  },
  {
    title: "Ticket de Avión",
    category: "Ocio",
    description: "Pasaje para un viaje a destinos increíbles.",
    imageUrl: "https://via.placeholder.com/200x150?text=Avion",
    points: 500,
    stock: 2,
  },
  {
    title: "Clase de Cocina Gourmet",
    category: "Ocio",
    description: "Aprendé a preparar platos gourmet.",
    imageUrl: "https://drive.google.com/u/0/drive-viewer/AKGpihYRPziHSiwVy_r0deMuGEOmTzlj3yThFZi8715[…]v7_uc_M7Uo6beyo-drAsKoMJ9Rf5Rk8iCd0owuH9PDEMkeI4=s1600-rw-v1",
    points: 400,
    stock: 5,
  },
  {
    title: "Parque Temático",
    category: "Ocio",
    description: "Día de emociones y diversión en un parque temático.",
    imageUrl: "https://via.placeholder.com/200x150?text=Park",
    points: 350,
    stock: 4,
  },
  {
    title: "Cena Romántica",
    category: "Ocio",
    description: "Una cena gourmet para dos personas.",
    imageUrl: "https://via.placeholder.com/200x150?text=Cena",
    points: 600,
    stock: 3,
  },
  {
    title: "Noche de Spa",
    category: "Ocio",
    description: "Disfrutá un día de spa en pareja.",
    imageUrl: "https://via.placeholder.com/200x150?text=Spa",
    points: 550,
    stock: 2,
  },
  {
    title: "Fin de Semana en la Playa",
    category: "Ocio",
    description: "Escapada romántica a la playa.",
    imageUrl: "https://via.placeholder.com/200x150?text=Playa",
    points: 800,
    stock: 1,
  },
  {
    title: "Cata de Vinos",
    category: "Ocio",
    description: "Participá en una cata de vinos exclusivos.",
    imageUrl: "https://via.placeholder.com/200x150?text=Vino",
    points: 500,
    stock: 4,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Ocio",
    description: "Clase personalizada con un experto en fitness.",
    imageUrl: "https://via.placeholder.com/200x150?text=Entrenamiento",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Ocio",
    description: "Accedé a un gimnasio premium durante un mes.",
    imageUrl: "https://via.placeholder.com/200x150?text=Gimnasio",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Ocio",
    description: "Participá en un maratón virtual.",
    imageUrl: "https://via.placeholder.com/200x150?text=Maraton",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Ocio",
    description: "Clase de yoga al aire libre.",
    imageUrl: "https://via.placeholder.com/200x150?text=Yoga",
    points: 350,
    stock: 5,
  },

  // Categoría: Disfrutar en Pareja
  {
    title: "Maratón de Películas",
    category: "Disfrutar en Pareja",
    description: "Un paquete de películas ilimitadas.",
    imageUrl: "https://via.placeholder.com/200x150?text=Cine1",
    points: 300,
    stock: 5,
  },
  {
    title: "Noche de Juegos",
    category: "Disfrutar en Pareja",
    description: "Noche de juegos con amigos o pareja.",
    imageUrl: "https://via.placeholder.com/200x150?text=Juegos",
    points: 350,
    stock: 4,
  },
  {
    title: "Concierto Virtual",
    category: "Disfrutar en Pareja",
    description: "Concierto en línea de tu artista favorito.",
    imageUrl: "https://via.placeholder.com/200x150?text=Concierto",
    points: 450,
    stock: 3,
  },
  {
    title: "Paseo Cinematográfico",
    category: "Disfrutar en Pareja",
    description: "Entradas para un cine de lujo.",
    imageUrl: "https://via.placeholder.com/200x150?text=Paseo",
    points: 400,
    stock: 3,
  },
  {
    title: "Cena Romántica",
    category: "Disfrutar en Pareja",
    description: "Una cena gourmet para dos personas.",
    imageUrl: "https://via.placeholder.com/200x150?text=Cena",
    points: 600,
    stock: 3,
  },
  {
    title: "Noche de Spa",
    category: "Disfrutar en Pareja",
    description: "Día de spa en pareja.",
    imageUrl: "https://via.placeholder.com/200x150?text=Spa",
    points: 550,
    stock: 2,
  },
  {
    title: "Fin de Semana en la Playa",
    category: "Disfrutar en Pareja",
    description: "Escapada romántica a la playa.",
    imageUrl: "https://via.placeholder.com/200x150?text=Playa",
    points: 800,
    stock: 1,
  },
  {
    title: "Cata de Vinos",
    category: "Disfrutar en Pareja",
    description: "Cata de vinos exclusivos.",
    imageUrl: "https://via.placeholder.com/200x150?text=Vino",
    points: 500,
    stock: 4,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Disfrutar en Pareja",
    description: "Clase con un entrenador experto.",
    imageUrl: "https://via.placeholder.com/200x150?text=Entrenamiento",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Disfrutar en Pareja",
    description: "Gimnasio premium por un mes.",
    imageUrl: "https://via.placeholder.com/200x150?text=Gimnasio",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Disfrutar en Pareja",
    description: "Participación en maratón virtual.",
    imageUrl: "https://via.placeholder.com/200x150?text=Maraton",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Disfrutar en Pareja",
    description: "Clase de yoga para dos.",
    imageUrl: "https://via.placeholder.com/200x150?text=Yoga",
    points: 350,
    stock: 5,
  },

  // Categoría: Deporte
  {
    title: "Maratón de Películas",
    category: "Deporte",
    description: "Películas ilimitadas para relajarte después de entrenar.",
    imageUrl: "https://via.placeholder.com/200x150?text=Cine1",
    points: 300,
    stock: 5,
  },
  {
    title: "Noche de Juegos",
    category: "Deporte",
    description: "Relajate después del ejercicio con una noche de juegos.",
    imageUrl: "https://via.placeholder.com/200x150?text=Juegos",
    points: 350,
    stock: 4,
  },
  {
    title: "Concierto Virtual",
    category: "Deporte",
    description: "Disfrutá de buena música post-entrenamiento.",
    imageUrl: "https://via.placeholder.com/200x150?text=Concierto",
    points: 450,
    stock: 3,
  },
  {
    title: "Paseo Cinematográfico",
    category: "Deporte",
    description: "Una buena peli después del gym.",
    imageUrl: "https://via.placeholder.com/200x150?text=Paseo",
    points: 400,
    stock: 3,
  },
  {
    title: "Cena Romántica",
    category: "Deporte",
    description: "Recompensá tu esfuerzo con una cena.",
    imageUrl: "https://via.placeholder.com/200x150?text=Cena",
    points: 600,
    stock: 3,
  },
  {
    title: "Noche de Spa",
    category: "Deporte",
    description: "Relajación total después del ejercicio.",
    imageUrl: "https://via.placeholder.com/200x150?text=Spa",
    points: 550,
    stock: 2,
  },
  {
    title: "Fin de Semana en la Playa",
    category: "Deporte",
    description: "Vacaciones deportivas y relax.",
    imageUrl: "https://via.placeholder.com/200x150?text=Playa",
    points: 800,
    stock: 1,
  },
  {
    title: "Cata de Vinos",
    category: "Deporte",
    description: "Un break elegante y merecido.",
    imageUrl: "https://via.placeholder.com/200x150?text=Vino",
    points: 500,
    stock: 4,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Deporte",
    description: "Nivelate con un coach de verdad.",
    imageUrl: "https://via.placeholder.com/200x150?text=Entrenamiento",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Deporte",
    description: "Mes completo de gym de primer nivel.",
    imageUrl: "https://via.placeholder.com/200x150?text=Gimnasio",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Deporte",
    description: "Participación en maratón a distancia.",
    imageUrl: "https://via.placeholder.com/200x150?text=Maraton",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Deporte",
    description: "Respirá profundo, estirá, repetí.",
    imageUrl: "https://via.placeholder.com/200x150?text=Yoga",
    points: 350,
    stock: 5,
  },
];

module.exports = rewards;
