const rewards = [
  {
    title: "Maratón de Películas",
    category: "Ocio",
    description: "Un paquete de suscripción para ver películas ilimitadas.",
    imageUrl: "/assets/cine.png",
    points: 300,
    stock: 5,
  },
  {
    title: "Ticket de Avión",
    category: "Ocio",
    description: "Pasaje para un viaje a destinos increíbles.",
    imageUrl: "/assets/avion.png",
    points: 500,
    stock: 2,
  },
  {
    title: "Clase de Cocina Gourmet",
    category: "Ocio",
    description: "Aprendé a preparar platos gourmet.",
    imageUrl: "/assets/cook.png",
    points: 400,
    stock: 5,
  },
  {
    title: "Parque Temático",
    category: "Ocio",
    description: "Día de emociones y diversión en un parque temático.",
    imageUrl: "/assets/park.png",
    points: 350,
    stock: 4,
  },
  {
    title: "Cena Romántica",
    category: "Ocio",
    description: "Una cena gourmet para dos personas.",
    imageUrl: "/assets/cena.png",
    points: 600,
    stock: 3,
  },
  {
    title: "Noche de Spa",
    category: "Ocio",
    description: "Disfrutá un día de spa en pareja.",
    imageUrl: "/assets/spa.png",
    points: 550,
    stock: 2,
  },
  {
    title: "Fin de Semana en la Playa",
    category: "Ocio",
    description: "Escapada romántica a la playa.",
    imageUrl: "/assets/globo.png",
    points: 800,
    stock: 1,
  },
  {
    title: "Cata de Vinos",
    category: "Ocio",
    description: "Participá en una cata de vinos exclusivos.",
    imageUrl: "/assets/copa.png",
    points: 500,
    stock: 4,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Ocio",
    description: "Clase personalizada con un experto en fitness.",
    imageUrl: "/assets/meta.png",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Ocio",
    description: "Accedé a un gimnasio premium durante un mes.",
    imageUrl: "/assets/gift_card.png",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Ocio",
    description: "Participá en un maratón virtual.",
    imageUrl: "/assets/star.png",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Ocio",
    description: "Clase de yoga al aire libre.",
    imageUrl: "/assets/dance.png",
    points: 350,
    stock: 5,
  },
  {
    title: "Maratón de Películas",
    category: "Disfrutar en Pareja",
    description: "Un paquete de películas ilimitadas.",
    imageUrl: "/assets/cine.png",
    points: 300,
    stock: 5,
  },
  {
    title: "Noche de Juegos",
    category: "Disfrutar en Pareja",
    description: "Noche de juegos con amigos o pareja.",
    imageUrl: "/assets/cuaderno.png",
    points: 350,
    stock: 4,
  },
  {
    title: "Concierto Virtual",
    category: "Disfrutar en Pareja",
    description: "Concierto en línea de tu artista favorito.",
    imageUrl: "/assets/music.png",
    points: 450,
    stock: 3,
  },
  {
    title: "Paseo Cinematográfico",
    category: "Disfrutar en Pareja",
    description: "Entradas para un cine de lujo.",
    imageUrl: "/assets/cine.png",
    points: 400,
    stock: 3,
  },
  {
    title: "Cena Romántica",
    category: "Disfrutar en Pareja",
    description: "Una cena gourmet para dos personas.",
    imageUrl: "/assets/cena.png",
    points: 600,
    stock: 3,
  },
  {
    title: "Noche de Spa",
    category: "Disfrutar en Pareja",
    description: "Día de spa en pareja.",
    imageUrl: "/assets/spa.png",
    points: 550,
    stock: 2,
  },
  {
    title: "Fin de Semana en la Playa",
    category: "Disfrutar en Pareja",
    description: "Escapada romántica a la playa.",
    imageUrl: "/assets/globo.png",
    points: 800,
    stock: 1,
  },
  {
    title: "Cata de Vinos",
    category: "Disfrutar en Pareja",
    description: "Cata de vinos exclusivos.",
    imageUrl: "/assets/copa.png",
    points: 500,
    stock: 4,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Disfrutar en Pareja",
    description: "Clase con un entrenador experto.",
    imageUrl: "/assets/meta.png",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Disfrutar en Pareja",
    description: "Gimnasio premium por un mes.",
    imageUrl: "/assets/gift_card.png",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Disfrutar en Pareja",
    description: "Participación en maratón virtual.",
    imageUrl: "/assets/star.png",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Disfrutar en Pareja",
    description: "Clase de yoga para dos.",
    imageUrl: "/assets/dance.png",
    points: 350,
    stock: 5,
  },
  {
    title: "Noche de Spa",
    category: "Deporte",
    description: "Relajación total después del ejercicio.",
    imageUrl: "/assets/spa.png",
    points: 550,
    stock: 2,
  },
  {
    title: "Entrenamiento Personalizado",
    category: "Deporte",
    description: "Nivelate con un coach de verdad.",
    imageUrl: "/assets/meta.png",
    points: 450,
    stock: 3,
  },
  {
    title: "Acceso a Gimnasio Premium",
    category: "Deporte",
    description: "Mes completo de gym de primer nivel.",
    imageUrl: "/assets/gift_card.png",
    points: 400,
    stock: 6,
  },
  {
    title: "Maratón Virtual",
    category: "Deporte",
    description: "Participación en maratón a distancia.",
    imageUrl: "/assets/star.png",
    points: 300,
    stock: 8,
  },
  {
    title: "Clase de Yoga al Aire Libre",
    category: "Deporte",
    description: "Respirá profundo, estirá, repetí.",
    imageUrl: "/assets/dance.png",
    points: 350,
    stock: 5,
  },
];

module.exports = rewards;
